<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text36_text36</name>
   <tag></tag>
   <elementGuidId>c2d2c3c4-a355-4020-a711-5547051cdfd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text36']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text36</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ca51106-2289-4a23-a3fc-65da45347e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc3c6bb5-71e5-4c77-9478-ae773b41faed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text36</value>
      <webElementGuid>af4141e4-7b08-4da3-81db-ab573cdeaf9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text36&quot;)</value>
      <webElementGuid>0e804e98-69b1-4fc2-937f-b4307c5db64a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text36']</value>
      <webElementGuid>95adb213-c97b-4f44-b853-334f00f2ed74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[36]</value>
      <webElementGuid>36e150fe-36c3-467d-bfd8-bdcc36fbc058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text36']</value>
      <webElementGuid>2519ced1-3977-470a-ae5e-7f031f1eb425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
