<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text11_text11</name>
   <tag></tag>
   <elementGuidId>9d24861b-c770-4868-823e-defe141d63d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text11']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2157200-f1f7-42ef-b4a3-36e8ef64dbe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1d28e16-d2d1-4346-8857-7335958efed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text11</value>
      <webElementGuid>7dafbd16-eb3b-44ff-a747-a1d90aab6114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text11&quot;)</value>
      <webElementGuid>46f29861-d7a4-4a9a-859c-029c9630b269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text11']</value>
      <webElementGuid>76a5ca9e-dca8-49eb-86db-3686a1627767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[11]</value>
      <webElementGuid>d72f646e-ec2c-4bc2-8094-e694e231fd5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text11']</value>
      <webElementGuid>cd037855-12c9-49fd-8716-eb2fe6ba686c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
