<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text28_text28</name>
   <tag></tag>
   <elementGuidId>0b3e3f56-3dc6-4567-9c3b-433304a79b1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2beff1d5-b187-4b94-9f75-767cfe9cdeea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f689bfc9-5477-43cf-9b2f-141e07093929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text28</value>
      <webElementGuid>cc20df47-345e-4f6d-a35b-896784aaa661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text28&quot;)</value>
      <webElementGuid>2c9308ea-7b3d-4823-835a-d3e247f32f2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text28']</value>
      <webElementGuid>80433a5c-7f20-4a75-9b4d-d7e32d6cbf58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[28]</value>
      <webElementGuid>bb6c0e8e-4d37-4018-8f5e-225698481136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text28']</value>
      <webElementGuid>88d6b066-cba5-47d7-89d4-2eb4a1fdab46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
