<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text22_text22</name>
   <tag></tag>
   <elementGuidId>ba1f08c2-97cc-4ec2-8dde-5f40f946533e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text22']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text22</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64503162-9453-4db1-8e83-85f2b093e516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1aa04d31-e486-456d-9fcd-411dd822cdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text22</value>
      <webElementGuid>1ac6f86c-7930-4442-a9b6-2d081b4d356d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text22&quot;)</value>
      <webElementGuid>4bd53ac3-7cac-4210-beda-c095ad98003d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text22']</value>
      <webElementGuid>46e15407-bedf-4a3c-8b5f-7c009d4b48e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[22]</value>
      <webElementGuid>101e3604-4148-45b0-8b81-d30d7b0e310f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text22']</value>
      <webElementGuid>40fa8986-6999-4560-9517-71e293227389</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
