<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text34_text34</name>
   <tag></tag>
   <elementGuidId>ffeead5f-ee80-405f-8c42-222d83e87a01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cd66848-b1d1-4bed-86b4-c337dd2a8bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>967409b4-630f-4191-9cc3-7a9b3ee2f649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text34</value>
      <webElementGuid>12631812-aabd-4cfa-899d-1e7a33e51b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text34&quot;)</value>
      <webElementGuid>6e95a947-2d4d-4c06-b1fe-304496f9b1ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text34']</value>
      <webElementGuid>a4070bd4-cc00-4a3b-8dcd-88f63b1c6665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[34]</value>
      <webElementGuid>ac9365bd-53da-451a-853d-81da3dbbf2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text34']</value>
      <webElementGuid>5463ee22-387f-46a0-97b2-a47ee44fec48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
