<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text40_text40</name>
   <tag></tag>
   <elementGuidId>ae046019-b903-40d8-b5ea-f342a7c936f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text40']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text40</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>523ce77c-5a69-4a8e-ab93-e5a076cfbcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56903de1-f7cf-4c30-8d24-bee0df6d0b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text40</value>
      <webElementGuid>8329566c-6842-4a2e-bf8a-307e66ef043c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text40&quot;)</value>
      <webElementGuid>78f19d64-24e6-48c0-86ab-e9404c88a67f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text40']</value>
      <webElementGuid>c8889928-5ba6-4c90-99b0-8d10ecfd671d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[40]</value>
      <webElementGuid>73cf7883-2827-43c2-b95d-acfbcea7c317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text40']</value>
      <webElementGuid>8e04d778-e90e-49c1-8c61-9be879d9f910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
