<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio4_radio5</name>
   <tag></tag>
   <elementGuidId>3b05d5ca-e27e-4b88-8b60-372e8034eb0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e81b800a-2d15-4107-8c49-baca3086968e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1a540cd6-98b3-4e53-ba87-13abbc160059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio5</value>
      <webElementGuid>20717edf-6ddb-4374-aea7-8e1d94d1e0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio5</value>
      <webElementGuid>8c473a1e-b281-40ef-9b88-814aecf2882a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio5&quot;)</value>
      <webElementGuid>6c74c654-4d4d-4fdd-940c-66260ff2348b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio5']</value>
      <webElementGuid>a05a30e0-4c1c-4529-b33e-4bd96874f373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[25]</value>
      <webElementGuid>fcab2f31-74ef-4e51-9c8f-4e5aa0276d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio5']</value>
      <webElementGuid>2c970fcf-1aac-4f8f-a5d8-ff167ce9c628</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
